# Generated by Django 2.2.7 on 2019-11-26 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('enrolled_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='General_employee',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('review', models.TextField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.General_employee')),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reservation_number', models.CharField(max_length=30)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.General_employee')),
            ],
        ),
        migrations.CreateModel(
            name='book_record',
            fields=[
                ('book_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('starting_rent', models.DateTimeField(default=django.utils.timezone.now)),
                ('finishing_rent', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.Book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.General_employee')),
            ],
        ),
    ]
