# Generated by Django 2.2.7 on 2019-11-26 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191126_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_employee',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
